AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  madison-reed-old-deployment-checker

  Checks for outdated CloudFormation stacks and deletes them based on the CleanupDate and static state.

Globals:
  Function:
    Timeout: 120
    MemorySize: 128

Resources:
  DeploymentCheckerLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaRole.Arn
      CodeUri: deploymentChecker/
      Handler: app.lambda_handler
      Runtime: python3.11
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 12 ? * 6 *) # Every Saturday at 12 PM

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationManagementPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:ListStacks
                  - cloudformation:DeleteStack
                Resource: '*'
